# Generated by Django 3.0.8 on 2020-07-07 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/')),
                ('birth_date', models.DateField()),
                ('hobbies', models.CharField(max_length=200)),
                ('about_me', models.TextField()),
                ('languages_know', models.ManyToManyField(related_name='know_languages', to='cards.Language')),
                ('languages_learn', models.ManyToManyField(related_name='learn_languages', to='cards.Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
