# Generated by Django 3.0.8 on 2020-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages_know',
            field=models.ManyToManyField(blank=True, related_name='know_languages', to='cards.Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages_learn',
            field=models.ManyToManyField(blank=True, related_name='learn_languages', to='cards.Language'),
        ),
    ]
