# Generated by Django 3.0.8 on 2020-07-15 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200715_1905'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200707_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, help_text='Some information about person', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar, picture', null=True, upload_to='images/avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date, when user is born', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, help_text='Hobbies of person, max length = 200', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages_know',
            field=models.ManyToManyField(blank=True, help_text='Languages person already know', related_name='know_languages', to='cards.Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages_learn',
            field=models.ManyToManyField(blank=True, help_text='Languages person would like to learn', related_name='learn_languages', to='cards.Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='This is the user, related to this profile', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
