# Generated by Django 3.0.8 on 2020-07-06 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the language name (e.g. English, Russian, German etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of cardset name (e.g. IT, sport, music etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter word', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cardset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of cardset', max_length=200)),
                ('last_revision_date', models.DateField(auto_now=True)),
                ('from_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_language', to='cards.Language')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ManyToManyField(help_text='Theme of the cardset', to='cards.Theme')),
                ('to_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_language', to='cards.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.Cardset')),
                ('native_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_word', to='cards.Word')),
                ('translate_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translate_name', to='cards.Word')),
            ],
        ),
    ]
