# Generated by Django 3.0.8 on 2020-07-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter the language name (e.g. English, Russian, German etc.), max symbols - 200', max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(help_text='A string value that represents word, max symbols - 200', max_length=200),
        ),
    ]
